### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by planetjoin** [rcschaff82/cwp_shoutcast2#1]
Hello

First of all.. thanks for your script .. it would be very useful!

I tried to install it twice.. the new itme appears in the left menu : "ShoutCast 2"
But opens blank page and at footer i get this error :

Fatal error: Uncaught ArgumentCountError: Too few arguments to function gitupdate::__construct(), 2 passed in /usr/local/cwpsrv/htdocs/resources/admin/modules/shoutcast2.php on line 307 and exactly 3 expected in /usr/local/cwpsrv/htdocs/resources/admin/modules/update_class.php:6 Stack trace: #0 /usr/local/cwpsrv/htdocs/resources/admin/modules/shoutcast2.php(307): gitupdate->__construct('rcschaff82', 'cwp_shoutcast2') #1 /usr/local/cwpsrv/htdocs/admin/admin/index.php(0): unknown() #2 {main} thrown in /usr/local/cwpsrv/htdocs/resources/admin/modules/update_class.php on line 6

I´m using :
CWPpro version: 0.9.8.1006
and using the old shoutcast plugin (1.98) i need to uninstall this before to install yours ?

Thanks for any help.
Fabian

**Comment by morrisond91** [comment]
Yeah i am getting the exact same issue as mentioned above, i don't have Shoutcast v1 installed tho.

**Comment by rcschaff82** [comment]
Sorry for the delay.  I never receive an email.  Corrected in the latest update.
